stages:
    - test

osx:
    stage: test
    script:
      - atbuild check

    tags:
      - xcode8
      - atbuild

linux:
    stage: test
    script:
        - apt-get update
        - apt-get install atbuild -y
        - atbuild check

    tags:
        - autoscale-linux
    image: drewcrawford/buildbase:latest