stages:
    - test
    - deploy

osx:
    stage: test
    script:
      - atbuild check

    tags:
      - xcode8
      - atbuild

linux:
    stage: test
    script:
        - apt-get update
        - apt-get install atbuild -y
        - atbuild check

    tags:
        - autoscale-linux
    image: drewcrawford/buildbase:latest

docs:
  stage: test
  script:
    - cd docs
    - make html
  tags:
    - autoscale-linux

  artifacts:
    paths:
      - docs/_build/html

  image: drewcrawford/anarchy-sphinx:latest

deploydocs:
  stage: deploy
  image: python:latest
  dependencies:
    - documentation
  script:
  - pip install awscli
  - aws s3 cp docs/_build/html/ s3://$DOC_BUCKET_NAME/ --recursive --acl "public-read"

  when: manual
  variables:
    DOC_BUCKET_NAME: "pianissimo-docs.sealedabstract.com"
  tags:
    - autoscale-linux